server.port=8080


brevo.api.key=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
brevo.sender.email=neelshah2411@gmail.com

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true